### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by AndrobaL** [JustYuuto/burger-king-fr-api#3]
Hello can you update for the latest version of the API ?

**Comment by AndrobaL** [comment]
any update ?

**Comment by CuteTenshii** [comment]
Which endpoints did you tried to use and did not worked

**Comment by AndrobaL** [comment]
The login one and it was a week ago

**Comment by AndrobaL** [comment]
any update ?

**Comment by AndrobaL** [comment]
nothing works because the login no longer works

**Comment by CuteTenshii** [comment]
I'm working on that, seems like they added otp codes :/ I'll try to see how can I implement this

**Comment by AndrobaL** [comment]
I hope you make it and please keep this post up to date, thank you
